### PR TITLE
Disable server-side volume handling.

### PR DESCRIPTION
**Pull request by padenot**
The API from pulseaudio is not coming, and this is causing user pain. We
can resurrect this code when we have an API to do what we want to do.

This fixes [BMO#1422637](https://bugzilla.mozilla.org/show_bug.cgi?id=1422637).

### CODE REVIEW

**Review by kinetiknz — APPROVED** [review]

**Comment by mara004** [comment]
Please merge into stable and esr - this server-side html5 volume control is annoying me.
Why do we need to wait for months until this fix takes effect?

**Comment by Termuellinator** [comment]
would really appreciate this, too

**Comment by mara004** [comment]
I don't really understand why PulseAudio allows at all for applications to set their own volume in the system mixer. This just doesn't make the remotest sense to me, only the user should be able to control the volume.
These inadvertent volume changes when listening to music on YouTube are just extremely annoying, I can't help but say this quite bluntly. I find this bug somewhat unbelievable, as it apparently exists since years and basically affects all Linux users.

**Comment by jomarocas** [comment]
ok what version say, i have lastest firefox and still dont working

**Comment by kinetiknz** [comment]
This was reverted in https://github.com/mozilla/cubeb-pulse-rs/pull/55, see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1422637#c16).

Please direct any further discussion to [bug 1422637](https://bugzilla.mozilla.org/show_bug.cgi?id=1422637).

**Pull request merged**
