### PR TITLE
 Use the input data ring buffer to count input frames read

### PR DESCRIPTION
**Pull request by padenot**
This is what we need. When starting a stream, there are two cases:
- There are already frames buffered in the ring buffer: we want to trim the input data to have just enough to not buffer
- There are no (or not enough) frames in the ring buffer: we want to provide silence to the callback

`get_linear_input_data()` underruns gracefully and fill the remaining space with silence.

### CODE REVIEW

**Comment by padenot** [comment]
@ChunMinChang, this is similar to what we do in the mac backend, conceptually, but there is a way to know how much is buffered there, to not trim when there is not enough data, instead of trimming in all cases and returning early when there's nothing to do.

**Review by ChunMinChang — COMMENTED** [review]
TBH, I don't understand why we need this change. This change implies: `input_frame_count` > `nframes` > _frames in input_buffer_manager_. Why is `input_frame_count` not equal to _frames in input_buffer_manager_?

If `input_frame_count` is the frame count of the frames in `input_buffer_manager`
https://github.com/djg/cubeb-pulse-rs/blob/3f48de5afcf81c6a71fd71d0d7403d57739e187a/src/backend/stream.rs#L319-L324
then we won't need to call `trim` when the frames needed (`nframes`) is smaller than frames within `input_buffer_manager`.

https://github.com/djg/cubeb-pulse-rs/blob/3f48de5afcf81c6a71fd71d0d7403d57739e187a/src/backend/stream.rs#L366-L372

The silent data can be appended right away without `trim`
https://github.com/djg/cubeb-pulse-rs/blob/3f48de5afcf81c6a71fd71d0d7403d57739e187a/src/backend/stream.rs#L377

If `input_frame_count` > `nframes` > _frames in input_buffer_manager_, then we may have a out-of-sync problem between `input_frame_count` and `input_buffer_manager`. I'd prefer we totally remove the `input_frame_count` and only use `input_buffer_manager` to calculate frames, if this is the case (IIRC, this is what macos backend does).


BTW, I suspect this is wrong:
https://github.com/djg/cubeb-pulse-rs/blob/3f48de5afcf81c6a71fd71d0d7403d57739e187a/src/backend/stream.rs#L371

`input_buffer_manager` contains *samples* rather than *frames*. Shouldn't it be something like:

`input_buffer_manager.trim(nframes * stm.input_sample_spec.frame_size() / stm.input_sample_spec.sample_size());`

Otherwise it only works when `frame_size() == sample_size()`

**Comment by padenot** [comment]
> If `input_frame_count` > `nframes` > _frames in input_buffer_manager_, then we may have a out-of-sync problem between `input_frame_count` and `input_buffer_manager`. I'd prefer we totally remove the `input_frame_count` and only use `input_buffer_manager` to calculate frames, if this is the case (IIRC, this is what macos backend does).

I'll do this, it's better.

**Review by ChunMinChang — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
