### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by ChunMinChang**
Fix a couple of clippy warnings

### CODE REVIEW

**Comment by ChunMinChang** [comment]
Should we run `cargo clippy` in GitHub action to catch some common mistakes in the following PRs?

**Review by kinetiknz — APPROVED** [review]
LGTM, thank you!

**Comment by kinetiknz** [comment]
> Should we run `cargo clippy` in GitHub action to catch some common mistakes in the following PRs?

Yeah, that'd be great.  We can also enable `cargo fmt` checks since existing issues were fixed in c3a51357f9674756311848bf1e5966a0b7c3eef9.

**Comment by kinetiknz** [comment]
> Yeah, that'd be great. We can also enable `cargo fmt` checks since existing issues were fixed in [c3a5135](https://github.com/mozilla/cubeb-pulse-rs/commit/c3a51357f9674756311848bf1e5966a0b7c3eef9).

Both enabled in ac1e4b5b17eb437de4038ba20bcaf51ec5ccb7f9.

**Pull request merged**
