### PR TITLE
Crash when a context is destroyed, per test expectations

### PR DESCRIPTION
**Pull request by padenot**

### CODE REVIEW

**Comment by padenot** [comment]
https://github.com/mozilla/cubeb/blob/master/src/cubeb_wasapi.cpp#L1808-L1809

**Comment by padenot** [comment]
https://treeherder.mozilla.org/logviewer?job_id=436376607&repo=try&lineNumber=3768 is how it errors on treeherder: this test is expected to crash.

**Review by kinetiknz — APPROVED** [review]
Thanks!

**Comment by padenot** [comment]
https://github.com/mozilla/cubeb-pulse-rs/commit/c04c4d2c7f2291cb81a1c48f5a8c425748f18cd8 turns out this is incorrect heh.

**Pull request merged**
